### PR TITLE
Replace getMetadata for row count with getQueryRowCount (which uses =COUNT(*))

### PR DESCRIPTION
**Pull request by dmpe**
https://github.com/Chicago/RSocrata/pull/64#issuecomment-156916015
this now takes care of:

> read.socrata(url = "https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5") generates an error because of the rowCount line. Specifically, I'm trying to understand the grander concept around getMetadata(), which is trying to fetch a lot of information, but is using little of it. Does it make sense to just keep it simple to help troubleshooting?

### CODE REVIEW

**Comment by dmpe** [comment]
THere is currently no way that travis will pass the tests as `rgdal` is 
namespace ‘rgdal’ 0.8-16 is being loaded, but >= 1.1.1 is required
https://www.google.de/search?client=ubuntu&channel=fs&q=rgdal+apk&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=JTROVoGFAafD8gehzoqYAQ#channel=fs&q=rgdal+ubuntu

I will check it out, later again

**Comment by dmpe** [comment]
Hi @tomschenkjr, 
After having totally messed up with this PR, I tried to recreate a lot which I have both committed (in the PR) and what has been in the repository before. 

Yeeh, most probably total mess. But, on the other hand, I fixed the error message with the one about curl and that the host could not have been resolved. :)

Let me know how can I help more in order to merge this PR. (I guess, you cannot merge it, right ?)

**Comment by tomschenkjr** [comment]
So, I'd like to propose that we step back a bit and increment through these new features a bit more incrementally. We can add a feature and make a pull request before moving onto the next one--break-up the larger pull request into smaller ones. I've opened a [Gitters forum](https://gitter.im/Chicago/RSocrata), which will let us discuss this a little more easily. 

I am thinking we work on features in these order: 
1. Add the ability to upload data sets (this will require the username and password parameter be added to arguments).
2. Add ability to download geojson data.

To get ready for this, I would recommend:
* We can set the `DESCRIPTION` file to `Version: 1.7.0-1` and with each build, get to `Version: 1.7.0-x` for ever how many `x` builds it'll take to get to a stable version with these new features.
*. Rebase the `dev` branch with the current `master`--stable--code as the starting point.

We should chat through this, though, to make sure it makes sense. If everyone is interested in this approach, jump into the forum and we can plan it out. We'll have to redo some of this work, but I think it's needed.

CC'ing @marks and @geneorama

**Comment by marks** [comment]
@tomschenkjr @dmpe - this (and nearly anything you all would decide) is completely A-OK with me. As I said in the Gitter channel:

> I am 100% cool with whatever you all decide. Just let me know when I should submit my changes (sounds like it may be easier to pull down the stable dev branch you all will create and re-do my changes, not a big deal).

**Pull request closed without merging**
