### PR TITLE
#58 support reading of private datasets & updating of datasets

### PR DESCRIPTION
**Pull request by marks**

### CODE REVIEW

**Comment by tomschenkjr** [comment]
AppVeyor came back with an error that's also likely to happen in Travis-CI. Seems like a simple fix. https://ci.appveyor.com/project/cityofchicago/rsocrata/build/1.0.95#L219

Also, quick reminder to sign the CLA: https://www.clahub.com/agreements/Chicago/RSocrata

**Comment by marks** [comment]
I have signed the CLA. Need to understand the Travis CI and AppVeyor failures.. everything tests :+1: on locally

**Comment by tomschenkjr** [comment]
Thanks.

It's not the unit tests, but when it's running R CMD check --as-cran

The NAMESPACE file mentions that plug is required. I think you just need to remove that because it doesn't appear that it's being used at all.

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
tom.schenk@cityofchicago.org
312-744-2770



On Tue, Jan 12, 2016 at 9:47 AM -0800, "Mark Silverberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have signed the CLA. Need to understand the Travis CI and AppVeyor failures.. everything tests [:+1:]  on locally

-
Reply to this email directly or view it on GitHub<https://github.com/Chicago/RSocrata/pull/70#issuecomment-170989297>.


________________________________
This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain legally privileged and/or confidential information. If you are not the intended recipient of this e-mail (or the person responsible for delivering this document to the intended recipient), you are hereby notified that any dissemination, distribution, printing or copying of this e-mail, and any attachment thereto, is strictly prohibited. If you have received this e-mail in error, please respond to the individual sending the message, and permanently delete the original and any copy of any e-mail and printout thereof.

**Comment by tomschenkjr** [comment]
From [this reply](https://github.com/travis-ci/travis-ci/issues/5447#issuecomment-171412101), the Travis CI build errrors were my fault. I need to rework the `.travis.yml.` 

I'm going to accept the pull request and make the needed changes to the file.

**Comment by marks** [comment]
Thanks @tomschenkjr . Any idea of when this might make it into master?

**Comment by tomschenkjr** [comment]
Soon. I'm working on some odd, gnarly Travis CI issues.

**Pull request merged**
