### PR TITLE
Fixes #183

### LINKED ISSUE #183: Failing CRAN checks - due 10/16
https://cran.r-project.org/web/checks/check_results_RSocrata.html

### PR DESCRIPTION
**Pull request by nicklucius**
Due to a change in an upstream data source, test code had broken. This fixes that code.

### CODE REVIEW

**Comment by geneorama** [comment]
I'm more inclined to remove the column count tests unless we can comment why they're relevant. 

I would also like to add some additional comments about what these tests are doing.

**Comment by nicklucius** [comment]
@geneorama I think we will have a better answer about the column questions when we resolve #184. The test description is "Warn instead of fail if X-SODA2-* headers are missing" and we could add to that after resolving #184 as well.

If you want to remove the column checks while #184 is open I don't see an issue with that.

**Comment by geneorama** [comment]
@nicklucius can you review please? 

Made changes based on our conversation. I don't think the checks for data frame or column numbers were related to the original issue. The column number check was the part that was failing, so to me the cleanest way is to adjust the test.

**Comment by geneorama** [comment]
Based on the verbal discussion, good idea to add the message relating to issue 118

**Comment by nicklucius** [comment]
Looks good @geneorama

**Review by geneorama — APPROVED** [review]

**Comment by geneorama** [comment]
@nicklucius thanks.  Glad we could get this knocked out.

**Pull request merged**
